### ISSUE TITLE
About SimpleCV installation troubleshoot

### ISSUE THREAD

**Issue by yanningzuo** [DeikiChen/Terminator-for-cat#1]
Hi Deiki,

I am wondering if you encountered any problem installing OpenCV (I guess its installation should be similar to SimpleCV). Currently, I am trying to install SimpleCV on raspberry pi 3 but encountered some problems. Could you help me with them?

I am following instructions from https://books.google.com/books?id=QMovDAAAQBAJ&pg=PA179&dq=installing+simplecv&hl=en&sa=X&ved=0ahUKEwjy1ceM8fbPAhXlsFQKHRk5DAMQ6AEIJDAB#v=onepage&q=installing%20simplecv&f=false. I succeeded in installing the first three packages but failed to install svgwrite. It seems to be a problem like this:https://bitbucket.org/mozman/svgwrite/issues/15/cant-import-svgwrite-116-_serialize_xml.

I also tried several times to install ElementTree but I think it failed. With my limited knowledge, I have no idea about what I should do... I am also attaching the commands and feedback for your reference. 

I would be most appreciate if you could possibly help me solving these problems! Thanks!

Yanning

**Comment by yanningzuo** [comment]
pi@.....:~ $ sudo pip install svgwrite
Downloading/unpacking svgwrite
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1178, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 194, in find_requirement
    page = self._get_page(main_index_url, req)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 568, in _get_page
    session=self.session,
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 694, in get_page
    req, link, "connection error: %s" % exc, url,
TypeError: __str__ returned non-string (type Error)

Storing debug log for failure in /root/.pip/pip.log

**Comment by yanningzuo** [comment]
pi@.....:~ $ sudo pip install http://svn.effbot.org/public/elementtree-1.3
Downloading/unpacking http://svn.effbot.org/public/elementtree-1.3
  Downloading elementtree-1.3 (unknown size): 264bytes downloaded
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1198, in prepare_files
    do_download,
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1376, in unpack_url
    self.session,
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 582, in unpack_http_url
    unpack_file(temp_location, location, content_type, link)
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 646, in unpack_file
    and is_svn_page(file_contents(filename))):
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 212, in file_contents
    return fp.read().decode('utf-8')
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x8b in position 1: invalid start byte

Storing debug log for failure in /root/.pip/pip.log

**Comment by DeikiChen** [comment]
Hi yanningzuo,

So sorry that I am never use SimpleCV before.
There is a tutorial about install OpenCV in Ubuntu 16.04, Hope to bring you
some inspiration.
http://www.pyimagesearch.com/2016/10/24/ubuntu-16-04-how-to-install-opencv/

2016-10-26 6:52 GMT+08:00 yanningzuo notifications@github.com:

**Comment by yanningzuo** [comment]
Thanks, Deiki! A bit different indeed. The problem turned out to be changed address of svgwrite...
